os: linux, macos
language: python
python:
  - 3.4
  - 3.7

before_install:
  - "export DISPLAY=:99.0"

install:
  - pip install --upgrade pip
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install numpy>=1.11.3 pandas>=0.19.2; fi
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package=package_template

after_success:
  - codecov