sudo: required
language: python
python:
  - 3.4
  - 3.5
  - 3.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install --upgrade pip
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install numpy==1.11.3 pandas==0.19.2; fi
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package=package_template

after_success:
  - codecov